### ISSUE TITLE
Set GitHub repo's Website field

### ISSUE THREAD

**Issue by cvrebert** [w3c/test-results#12]
The field that I'm referring to:
![5fe281e4-cb33-11e3-9c21-b12e0c2236a0](https://cloud.githubusercontent.com/assets/419884/5326219/3169de40-7cc0-11e4-9e2b-6e5142cd9dd4.png)

Presumably, for this repo, it should be set to something under https://w3c.github.io/test-results/

**Comment by sideshowbarker** [comment]
> Presumably, for this repo, it should be set to something under https://w3c.github.io/test-results/

For now I've just set it to https://w3c.github.io/test-results/README.md. I don't have any other good ideas about what else to set it to, other than just https://github.com/w3c/test-results, which would seem kind of pointless.

Anyway, the github UI makes it clear that this field is optional, so it seems maybe not reliable to depend on anything being there for any particular repo. But If there's some problem that'd be solve by setting it some something more useful, please go ahead and reopen this with a suggestion.

**Comment by darobin** [comment]
The field is optional, but it could be useful to have an index in there. We could have a commit hook generate an index page pointing to all the result pages. Certainly not urgent, nice to have if someone has a bit of time.
